version: '3.8'
services:
  nginx:
    # 直接拿 nginx official image 來使用 
    image: library/nginx:1.19-alpine
    container_name: "dev_nginx"
    ports:
      - 80:80
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./app:/var/www/html"
  php:
    # PHP 常常要設定執行環境或其他 extensions ，另外 build image 使用
    image: "dev_php"
    build: ./php
    container_name: "dev_php"
    ports:
      - 9000:9000
    volumes:
      - "./app:/var/www/html"